// <auto-generated />
using InlamningsuppgiftEntity;
using InlamningsuppgiftEntity.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InlamningsuppgiftEntity.Migrations
{
    [DbContext(typeof(GenealogiContext))]
    [Migration("20211218115844_newTry")]
    partial class newTry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InlamningsuppgiftEntity.GenealogiCRUD", b =>
                {
                    b.Property<string>("DatabaseName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxRows")
                        .HasColumnType("int");

                    b.Property<string>("OrderBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DatabaseName");

                    b.ToTable("MyRelatives");
                });
#pragma warning restore 612, 618
        }
    }
}
